task 2 and 3

diff --git a/lab3/task1 b/lab3/task1
--- a/lab3/task1
+++ b/lab3/task1
@@ -4,8 +4,8 @@ mkdir ~/test 2>/dev/null && {
 	echo "catalog test was created succesfully" > ~/report
 	touch ~/test/"$tmp"
 }
-ping 'www.net_nikogo' 2>/dev/null || {
-	tmp=$(date +%m-%d-%y_%H:%M:%S)
-	echo "$tmp Error" >> ~/report
+ping 'www.net_nikogo.ru' 2>/dev/null || {
+	tmp1=$(date +%m-%d-%y_%H:%M:%S)
+	echo "$tmp1 Error" >> ~/report
 }
 
